### ISSUE TITLE
Get Chat Error ReferenceError: _ is not defined

### ISSUE THREAD

**Issue by Grace-ZhuZhu** [alamorre/react-chat-engine#104]
Hi I get the following error:

> Get Chat Error ReferenceError: _ is not defined
    at onGetChat (ChatSocket.js:71)
    at ChatSocket.js:91
    at getChat.js:12

The reason is straightforward, `import _ from 'lodash'` is missing in _ChatSocket.js_
Could you please fix this one liner issue, thank you very much!

**Comment by alamorre** [comment]
Good catch! Resolved in `1.11.21` 👍
