### ISSUE TITLE
Requests stopped working and now I cant create a new account/project (my bachelors degree depends on this)

### ISSUE THREAD

**Issue by gerpet2** [alamorre/react-chat-engine#135]
Okay so this is a serious situation.

I am using chatengine.io in my bachelors project and I am due to present it next week. Everything worked fine until I decided to rehearse the presentation today. I tried various requests to chatengine's API and every time I got 403 FORBIDDEN error. I checked the private key, project ID, all seemed to be correct.

I didn't know how to get help, tried writing in the chat on the website, didn't get an answer. I saw that here, on issues, someone wrote about the 403 error and no there was no reply.
I thought that maybe I should just create a new project, but I couldn't find an option to do so.
So I deleted my project.
And then I couldn't find an option to create a new project again.
So I deleted my account to create a new one.
And then there's this message that **I CAN'T CREATE A NEW ACCOUNT.**

Could you please somehow help me get an account, I can pay a fee to have it, **I need a working account for a month.**

**Comment by Mirella-H** [comment]
Hello gerpet, so I have the same problem as you I hope you found a way to solve it. If you did could you please tell me how you got it to work.
