### ISSUE TITLE
I keep getting a socket error/ socket closed while loop 

### ISSUE THREAD

**Issue by lilytava2510** [alamorre/react-chat-engine#139]
When ever I want to start trying to start a chat I get a socket closed/ socket error while loop and I don't know how to solve this problem.

**Comment by alamorre** [comment]
Can you share the errors logs that you see in the console?

**Comment by arifdroid** [comment]
me too , getting the same error 

<img width="509" alt="Screenshot 2022-07-12 at 11 15 58 PM" src="https://user-images.githubusercontent.com/47731516/178524970-e34df2e2-9999-49f6-af6f-a72f7b811a10.png">

![Screenshot 2022-07-12 at 11 15 27 PM](https://user-images.githubusercontent.com/47731516/178524821-44799db7-4e8a-452a-810c-1ab45cdb0bcd.png)


![Screenshot 2022-07-12 at 11 13 58 PM](https://user-images.githubusercontent.com/47731516/178524489-255e4b4f-40c8-413a-8c2e-e24e448d331c.png)

**Comment by RubenF01** [comment]
I'm also experiencing this issue... Is there a fix??

**Comment by sagarbrathod1** [comment]
same here...

**Comment by markibanez** [comment]
Same here!

**Comment by Rahulmall** [comment]
same here

**Comment by pint-drinker** [comment]
experiencing this as well in a loop when using the react-chat-engine-pretty default example. Experiencing a websocket error using the most basic ChatEngine example as well.
`index.js:80 WebSocket connection to 'wss://api.chatengine.io/person_v4/?session_token=st-6980cff5-f563-4f58-893c-27c8d4b356eb' failed: WebSocket is closed before the connection is established.`

**Comment by alamorre** [comment]
Turn off react strictmode 👍👍

**Comment by pint-drinker** [comment]
@alamorre you are a legend man. Thank you for the quick turn reply!
