### ISSUE TITLE
Chat suddenly stopped working, projects disappeared from Chatengine.io, I'm not free user

### ISSUE THREAD

**Issue by amer1x** [alamorre/react-chat-engine#140]
I'm getting 403 errors, with message that my credentials are not correct even though they worked couple of days ago, and I didn't change anything. I'm subscribed to Light plan but now I can't see any of my projects and I can't even unsubscribe from current plan or change it. Chat on Chatengine.io is also not working. This feels like a scam if I'm honest...

**Comment by alamorre** [comment]
Hello! You can share your email with adam@lamorre.co and we can see what happened to your project.

I assume you didn't complete the checkout session and the project was deleted upon expiry. But if I'm wrong we'll happily refund you. Again, please email us specifics.

**Comment by amer1x** [comment]
Issues resolved due to some web-hook that deleted the projects, and Adam fixed it so it shouldn't happen in the future.
