### ISSUE TITLE
ERESOLVE: unable to resolve dependency tree during npm install

### ISSUE THREAD

**Issue by OkoliEvans** [alamorre/react-chat-engine#145]
![chatbox err](https://user-images.githubusercontent.com/95226065/186447223-2e4ea6ab-68d3-45df-a6ba-04b9d40bc7f1.PNG)

I am getting the above error when I try to install react chat engine. The react version is 18.0.0. I  installed react-chat-engine --legacy-peer-deps, and I got an error 'module not found, could not resolve react-chat-engine'.

**Comment by OkoliEvans** [comment]
Another issue I encounter is on the chatengine.io website. I forgot my password, I have been requesting a reset on the forgot password link, but I never get any mails.
![issuePWReset](https://user-images.githubusercontent.com/95226065/186451471-154f26cc-bc38-4ee5-86cb-d74f67b50921.PNG)

**Comment by ayushbh2020** [comment]
@OkoliEvans Did you solve this ever?

**Comment by alamorre** [comment]
Hey I added the following line to package.json

```
"peerDependencies": {
    "react": "^16.8.0 || ^17.0.1 || ^18.0.0"
},
```

Should support react 18.0.0 and up now!

**Comment by OkoliEvans** [comment]
Awesome. But I tried logging in to your website, it doesn't authenticate my
credentials, and it doesn't send reset link too. I was able to register
only, and it kept charging me monthly payments for some months... even
though the payments have now stopped.
