### ISSUE TITLE
input throttling

### ISSUE THREAD

**Issue by moonkorea00** [alamorre/react-chat-engine#156]
Hey Adam,

I'm getting a 429 status code whenever i update the input field in the chat feed component.

the request details are as below : 
Request URL : `https://api.chatengine.io/chats/139361/typing/`
Response message : detail: `"Request was throttled. Expected available in 1 second."`

Is this an intentional feature or is it only expected on the free tier? 

Multiple space bar keypresses dont work as well.

![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/78708082/209895081-a3c2fbf4-015b-4cb4-bf23-c327f93b92c6.gif)

**Comment by m-grig** [comment]
Also running into this issue. And the first space bar press appears to give no input. It always requires two spacebar presses to add a space character.

**Comment by pint-drinker** [comment]
yes i am also seeing this as well. The space bar presses is the major issue for me. I may resort to a custom new massage form renderer in the interim. Here is a video demoing the space bar issues:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/55985967/224582978-fa7f5393-a02b-41a5-a286-cc816f412bb4.gif)

Perhaps it has something to do with this line of code? where things are getting trimmed: https://github.com/chatengine-io/react-chat-engine/blob/master/src/components/ChatEngine/ChatFeed/NewMessageForm/index.js#L39

**Comment by alamorre** [comment]
Input throttling is not an issue. It just limits the number of times you tell the server you changed the input field. 

Again, do not worry when you see this response 👍

**Comment by pint-drinker** [comment]
i'll open a separate issue for the spacebar input problem

**Comment by moonkorea00** [comment]
> Input throttling is not an issue. It just limits the number of times you tell the server you changed the input field.
> 
> Again, do not worry when you see this response 👍

I see, but is the issue regarding the spacebar intentional as well?

cheers.
