### ISSUE TITLE
Socket Error; Socket Closed

### ISSUE THREAD

**Issue by lixx21** [alamorre/react-chat-engine#160]
![image](https://user-images.githubusercontent.com/91602612/224891431-819466fd-c363-421e-a0db-ff916eb030bf.png)

I need help to solved this issue because I already watched the youtube tutorial and I have make sure that I have followed all steps

**Comment by imanmalhi** [comment]
Having the same issue. Tried different projects ids and still the same. It pushes the credentials but is unable to hold the connection. Server issue on chatengine end perhaps.

**Comment by abdulragib** [comment]
i am also facing same issues with react-chat-engine

**Comment by alamorre** [comment]
Turn off react strictmode 👍
